# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fb09ebac10ba035117777e15e11b8d652bea7a5c5aaead1d85b2f56618c27cc47dbd013259fa25d4ef5b27fd7e24ccd5e2167113f220cbbeb306744c9a4d219

test:
  secret_key_base: 1598c997c594439029a409f28ba0bb127be14cedc3581ddf7d996e10cb82d60664cd06407e480d021bff70acef8ac2f4ded01cd036c1942c60b067abfabc26db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
